# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  node: circleci/node@4.7
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  cicd-job:
    executor:
      name: node/default
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
        name: install dependencies - NPM fpackage
        command: npm i
      - run:
        name: run tests
        command: npm run test
      - run:
        name: run linter
        command: npm run lint

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  push-workflow:
    jobs:
      - cicd-job
